name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests
        run: |
          go test ./internal/... ./pkg/... -v -race -coverprofile=coverage.txt -covermode=atomic

      - name: Setup for E2E tests
        run: |
          sudo apt-get update
          sudo apt-get install -y iptables
          # Create test directories with proper permissions
          sudo mkdir -p /tmp/spip-test /tmp/spip-test-tls
          sudo chmod 777 /tmp/spip-test /tmp/spip-test-tls
          # Allow the test user to use iptables without password
          echo "runner ALL=(ALL) NOPASSWD: /usr/sbin/iptables" | sudo tee /etc/sudoers.d/runner-iptables
          echo "runner ALL=(ALL) NOPASSWD: /sbin/iptables" | sudo tee -a /etc/sudoers.d/runner-iptables
        
      - name: Run E2E tests
        run: |
          cd test/e2e
          sudo -E go test -v ./... -race 